### ISSUE TITLE
Varnish dashboard doesn't work

### ISSUE THREAD

**Issue by samueloph** [DataDog/the-monitor#63] opened 2017-11-06 11:54 UTC
The dashboard showed at https://github.com/DataDog/the-monitor/blob/master/varnish/monitor_varnish_using_datadog.md is blank.

This is probably related to https://github.com/DataDog/dd-agent/issues/1459

Anyone willing to follow the guide will end up with a blank dashboard wondering if something went wrong, but seeing the graphs from "infrastructure->apps->varnish" is possible.

Is there a way i can fix the dashboard (".MAIN.") without having to rewrite everything?

edit-> varnish 5.2 and datadog-agent-5.18.1

**Comment by johnaxel** [comment] 2017-11-14 23:28
Thanks for the report, @samueloph — I've reproduced this issue, which appears to be due to the way the metrics are being processed by the Agent rather than the design of the dashboard. I just opened an issue on the integration repo to let our developers know that the metrics are apparently not being mapped to the correct names for very recent versions of Varnish.

**Comment by johnaxel** [comment] 2018-01-31 21:35
Looks like this should have been fixed by the linked [PR](https://github.com/DataDog/integrations-core/issues/871), so I'm going to close this issue. Thanks again for the report @samueloph

**Closed by johnaxel** 2018-01-31 21:35 UTC
